// libs/braid-react/src/lib/braid-fragment.tsx
import { useCallback, useEffect, useImperativeHandle, useRef, useState, type Ref } from 'react';
import type { FragmentSlotState } from '@braidlabs/core';

/** The `detail` of a `braid:error` event. */
export interface BraidFragmentError {
  fragmentId: string;
  stage: string;
  fixHint?: string;
  error: Error;
}

/** The `detail` of a fragment-to-host `braid:event`. */
export interface BraidFragmentEvent {
  type: string;
  detail: unknown;
}

/** Imperative handle, for hosts that need to force a fragment to boot again. */
export interface BraidFragmentHandle {
  reload(): Promise<void>;
  readonly state: FragmentSlotState;
}

export interface BraidFragmentProps {
  /** The fragment id, as registered in the gateway. */
  name: string;
  /**
   * A fixed route for the fragment. Omit it and the fragment is *bound*: it follows the host's
   * location, and navigations it performs drive the host URL.
   */
  src?: string;
  /** Props handed to the fragment. Structured-cloned across the realm boundary. */
  props?: Record<string, unknown>;
  onReady?: (detail: { fragmentId: string }) => void;
  onError?: (detail: BraidFragmentError) => void;
  onFragmentEvent?: (detail: BraidFragmentEvent) => void;
  /** Called whenever the fragment's lifecycle state changes. */
  onStateChange?: (state: FragmentSlotState) => void;
  className?: string;
  style?: React.CSSProperties;
  ref?: Ref<BraidFragmentHandle>;
}

type SlotElement = HTMLElement & {
  props?: Record<string, unknown>;
  state?: FragmentSlotState;
  reload?: () => Promise<void>;
};

/**
 * Renders a Braid fragment.
 *
 * ```tsx
 * <BraidFragment name="billing" onReady={() => …} />
 * ```
 *
 * A typed shim over the `<fragment-slot>` custom element. It renders the element during SSR too,
 * which is what lets the gateway pierce the fragment's server-rendered markup into the page —
 * only the event wiring is browser-only.
 *
 * `props` is assigned as a DOM *property* rather than an attribute: it crosses the realm boundary
 * by structured clone, so serializing it to a string would be wrong.
 */
export function BraidFragment({
  name,
  src,
  props,
  onReady,
  onError,
  onFragmentEvent,
  onStateChange,
  className,
  style,
  ref,
}: BraidFragmentProps) {
  const slotRef = useRef<SlotElement>(null);
  const [, setState] = useState<FragmentSlotState>('idle');

  // handlers live in a ref so re-renders never re-subscribe the listeners
  const handlers = useRef({ onReady, onError, onFragmentEvent, onStateChange });
  handlers.current = { onReady, onError, onFragmentEvent, onStateChange };

  useEffect(() => {
    const slot = slotRef.current;
    if (!slot) return;

    const controller = new AbortController();
    const listen = <T,>(type: string, handle: (detail: T) => void) =>
      slot.addEventListener(
        type,
        (event) => {
          const next = slot.state ?? 'idle';
          setState(next);
          handlers.current.onStateChange?.(next);
          handle((event as CustomEvent<T>).detail);
        },
        { signal: controller.signal },
      );

    listen<{ fragmentId: string }>('braid:ready', (detail) => handlers.current.onReady?.(detail));
    listen<BraidFragmentError>('braid:error', (detail) => handlers.current.onError?.(detail));
    listen<BraidFragmentEvent>('braid:event', (detail) => handlers.current.onFragmentEvent?.(detail));

    return () => controller.abort();
  }, []);

  // a property, never a serialized attribute
  useEffect(() => {
    const slot = slotRef.current;
    if (slot && props !== undefined) slot.props = props;
  }, [props]);

  const reload = useCallback(async () => {
    await slotRef.current?.reload?.();
  }, []);

  useImperativeHandle(ref, () => ({ reload, get state() { return slotRef.current?.state ?? 'idle'; } }), [reload]);

  return (
    <fragment-slot
      ref={slotRef}
      name={name}
      {...(src === undefined ? {} : { src })}
      class={className}
      style={style}
    />
  );
}

/**
 * `<fragment-slot>` is a custom element, so React needs to be told it exists — declared here,
 * once, rather than by every host that renders a fragment.
 */
declare module 'react' {
  /* eslint-disable-next-line @typescript-eslint/no-namespace -- React 19 moved
     JSX.IntrinsicElements into a namespace inside the `react` module; augmenting it has no
     module-syntax equivalent. */
  namespace JSX {
    interface IntrinsicElements {
      'fragment-slot': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        name?: string;
        src?: string;
        class?: string;
        ref?: React.Ref<SlotElement | null>;
      };
    }
  }
}

// libs/braid-angular/src/lib/braid-fragment.ts
import {
  afterNextRender,
  Component,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import type { FragmentSlotState } from '@braidlabs/core';

/** The `detail` of a `braid:error` event, surfaced through the `failed` output. */
export interface BraidFragmentError {
  fragmentId: string;
  stage: string;
  fixHint?: string;
  error: Error;
}

/** The `detail` of a fragment-to-host `braid:event`. */
export interface BraidFragmentEvent {
  type: string;
  detail: unknown;
}

/**
 * Renders a Braid fragment.
 *
 * ```html
 * <braid-fragment name="billing" (ready)="onReady()" />
 * ```
 *
 * A thin, typed shim over the `<fragment-slot>` custom element. What it buys over using the
 * element directly:
 *
 * - **No `CUSTOM_ELEMENTS_SCHEMA` in your components.** The schema is declared here, once, so
 *   your templates keep their strict element checking.
 * - **Typed inputs and outputs.** `props` is an object rather than a JSON-encoded attribute, and
 *   events arrive as typed outputs rather than `CustomEvent` listeners you wire by hand.
 * - **The slot still renders during SSR**, which is what lets the gateway pierce the fragment's
 *   server-rendered markup into it. Only the event wiring is browser-only.
 */
@Component({
  selector: 'braid-fragment',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<fragment-slot #slot [attr.name]="name()" [attr.src]="src() ?? null"></fragment-slot>`,
  styles: `
    :host,
    fragment-slot {
      display: block;
    }
  `,
})
export class BraidFragment {
  /** The fragment id, as registered in the gateway. */
  readonly name = input.required<string>();

  /**
   * A fixed route for the fragment. Omit it and the fragment is *bound*: it follows the host's
   * location, and navigations it performs drive the host URL.
   */
  readonly src = input<string>();

  /** Props handed to the fragment. Structured-cloned across the realm boundary. */
  readonly props = input<Record<string, unknown>>();

  /** The fragment booted and is running. */
  readonly ready = output<{ fragmentId: string }>();
  /** The fragment failed to boot; the detail names the stage and the likely fix. */
  readonly failed = output<BraidFragmentError>();
  /** The fragment emitted an event to the host. */
  readonly fragmentEvent = output<BraidFragmentEvent>();

  private readonly slotRef = viewChild.required<ElementRef<HTMLElement>>('slot');
  private readonly slotState = signal<FragmentSlotState>('idle');

  /** The fragment's lifecycle state, for templates that want to show their own placeholder. */
  readonly state = computed(() => this.slotState());

  constructor() {
    const destroyRef = inject(DestroyRef);

    // Props are a property, not an attribute: they cross the realm boundary by structured
    // clone, so they are never serialized to a string.
    effect(() => {
      const props = this.props();
      const slot = this.slotRef().nativeElement as HTMLElement & { props?: Record<string, unknown> };
      if (props !== undefined) slot.props = props;
    });

    // Browser-only: on the server the element is rendered so the gateway has something to
    // pierce into, but there is nothing to listen to.
    afterNextRender(() => {
      const slot = this.slotRef().nativeElement as HTMLElement & { state?: FragmentSlotState };
      const controller = new AbortController();
      const listen = <T>(type: string, handle: (detail: T) => void) =>
        slot.addEventListener(
          type,
          (event) => {
            this.slotState.set(slot.state ?? 'idle');
            handle((event as CustomEvent<T>).detail);
          },
          { signal: controller.signal },
        );

      listen<{ fragmentId: string }>('braid:ready', (detail) => this.ready.emit(detail));
      listen<BraidFragmentError>('braid:error', (detail) => this.failed.emit(detail));
      listen<BraidFragmentEvent>('braid:event', (detail) => this.fragmentEvent.emit(detail));

      this.slotState.set(slot.state ?? 'loading');
      destroyRef.onDestroy(() => controller.abort());
    });
  }

  /** Tears the fragment down and boots it again from the network. */
  async reload(): Promise<void> {
    const slot = this.slotRef().nativeElement as HTMLElement & { reload?: () => Promise<void> };
    await slot.reload?.();
  }
}
